# Generated by Django 3.0.7 on 2021-06-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210618_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='year_semester',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Semester'),
        ),
    ]
