# Generated by Django 3.0.7 on 2021-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studentprofile_year_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(default='teacher.jpeg', upload_to='profile_pic_teacher'),
        ),
    ]
