# Generated by Django 3.0.7 on 2021-06-20 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_teacher_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Batch'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Dept'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Semester'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Dept'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
