# Generated by Django 2.2.7 on 2021-07-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_studentprofile_retake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='retake',
        ),
    ]
