# Generated by Django 3.0.7 on 2021-06-18 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('typ1', models.CharField(blank=True, max_length=20)),
                ('typ2', models.CharField(blank=True, max_length=20)),
                ('typ3', models.CharField(blank=True, max_length=20)),
                ('typ4', models.CharField(blank=True, max_length=20)),
                ('typ5', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=200)),
                ('teacher', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('point', models.IntegerField(default=100)),
                ('session', models.CharField(max_length=50)),
                ('question', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('dept', models.CharField(blank=True, max_length=250)),
                ('subcode', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('semester', models.CharField(choices=[('1st year 1st semester', '1st year 1st semester'), ('1st year 2nd semester', '1st year 2nd semester'), ('2nd year 1st semester', '2nd year 1st semester'), ('2nd year 2nd semester', '2nd year 2nd semester'), ('3rd year 1st semester', '3rd year 1st semester'), ('3rd year 2nd semester', '3rd year 2nd semester'), ('4th year 1st semester', '4th year 1st semester'), ('4th year 2nd semester', '4th year 2nd semester')], default='1st year 1st semester', max_length=50)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('revpoint', models.CharField(blank=True, max_length=1000)),
                ('given', models.TextField(blank=True)),
                ('totalpoint', models.IntegerField(default=0)),
                ('avg', models.IntegerField(blank=True, default=0, null=True)),
                ('question', models.ManyToManyField(to='main.Question')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Teacher')),
            ],
        ),
    ]
