# Generated by Django 3.0.7 on 2021-06-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studentprofile_year_semester'),
        ('main', '0002_auto_20210618_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject')),
            ],
        ),
        migrations.DeleteModel(
            name='SemesterDeptSubject',
        ),
    ]
