# Generated by Django 3.0.7 on 2021-06-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210618_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subcode']},
        ),
    ]
