# Generated by Django 3.0.7 on 2021-06-18 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studentprofile_year_semester'),
        ('main', '0005_auto_20210618_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='typ1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='typ2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='typ3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='typ4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='typ5',
        ),
        migrations.RemoveField(
            model_name='review',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='review',
            name='session',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='review',
            name='teacher',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewfor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.ReviewSet'),
        ),
        migrations.AlterField(
            model_name='review',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question'),
        ),
        migrations.AlterField(
            model_name='reviewset',
            name='avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewset',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reviewset',
            name='semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Semester'),
        ),
        migrations.AlterField(
            model_name='reviewset',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='reviewset',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Teacher'),
        ),
    ]
