# Generated by Django 3.0.7 on 2021-06-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210618_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewset',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='reviewset',
            name='given',
        ),
        migrations.RemoveField(
            model_name='reviewset',
            name='revpoint',
        ),
        migrations.RemoveField(
            model_name='reviewset',
            name='totalpoint',
        ),
        migrations.CreateModel(
            name='ReviewDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revpoint', models.CharField(blank=True, max_length=1000)),
                ('given', models.TextField(blank=True)),
                ('totalpoint', models.IntegerField(default=0)),
                ('avg', models.IntegerField(default=0)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ReviewSet')),
            ],
        ),
    ]
