# Generated by Django 3.0.7 on 2021-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210618_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdetails',
            name='given',
            field=models.IntegerField(default=0),
        ),
    ]
