# Generated by Django 3.0.7 on 2021-06-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210618_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdetails',
            name='avg',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='reviewdetails',
            name='totalpoint',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
