# Generated by Django 3.0.7 on 2021-06-19 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_studentprofile_year_semester'),
        ('main', '0011_auto_20210618_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewset',
            name='dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Dept'),
        ),
        migrations.AddField(
            model_name='reviewset',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
