# Generated by Django 2.2.7 on 2021-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210620_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdetails',
            name='given',
            field=models.TextField(blank=True),
        ),
    ]
